'use strict';
const $=s=>document.getElementById(s), KEY='atable-v1-save';
const catalog={table:{name:'Table bistro',price:65,w:1.3,d:1.1},chair:{name:'Chaise sauge',price:20,w:.52,d:.56},till:{name:'Caisse',price:70,w:1,d:.7},fridge:{name:'Réfrigérateur',price:100,w:.85,d:.8},prep:{name:'Plan de travail',price:65,w:1.4,d:.75},stove:{name:'Plaque de cuisson',price:90,w:1,d:.8}};
const customerNames=['Lina','Noah','Jade','Malo','Inès','Louis','Nina','Sacha','Maya','Tom','Zoé','Eliott','Léa','Adam','Lou','Nolan'];
const setupLabels={table:'table',chair:'chaise',till:'caisse',fridge:'réfrigérateur',prep:'plan de travail',stove:'plaque de cuisson'};
function clientName(c){return customerNames[(Math.max(1,c?.id||1)-1)%customerNames.length];}
function setupState(){const counts=Object.fromEntries(Object.keys(catalog).map(t=>[t,S.furniture.filter(f=>f.type===t).length]));return {counts,missing:[['table',1],['chair',2],['till',1],['fridge',1],['prep',1],['stove',1]].filter(([t,n])=>counts[t]<n)};}
function marketIcon(type){const common='viewBox="0 0 120 82" aria-hidden="true"';switch(type){case'table':return `<svg ${common}><ellipse cx="60" cy="69" rx="40" ry="5" fill="#173b3520"/><rect x="22" y="25" width="76" height="12" rx="5" fill="#bd8e59"/><rect x="29" y="36" width="7" height="31" rx="2" fill="#536b62"/><rect x="84" y="36" width="7" height="31" rx="2" fill="#536b62"/><circle cx="60" cy="22" r="6" fill="#efe3c1"/></svg>`;case'chair':return `<svg ${common}><ellipse cx="60" cy="70" rx="28" ry="4" fill="#173b3520"/><rect x="39" y="24" width="42" height="10" rx="4" fill="#719478"/><rect x="41" y="9" width="38" height="24" rx="5" fill="#719478"/><rect x="43" y="33" width="6" height="34" rx="2" fill="#536b62"/><rect x="71" y="33" width="6" height="34" rx="2" fill="#536b62"/></svg>`;case'till':return `<svg ${common}><ellipse cx="60" cy="70" rx="39" ry="4" fill="#173b3520"/><rect x="24" y="35" width="72" height="30" rx="6" fill="#bd8e59"/><rect x="31" y="29" width="58" height="8" rx="3" fill="#efe7d3"/><path d="M47 28l7-18h29l8 18z" fill="#536b62"/><rect x="58" y="14" width="21" height="10" rx="2" fill="#dcebb4"/><text x="68.5" y="22" text-anchor="middle" font-size="10" font-weight="800" fill="#27493f">€</text></svg>`;case'fridge':return `<svg ${common}><ellipse cx="60" cy="72" rx="31" ry="4" fill="#173b3520"/><rect x="38" y="8" width="44" height="62" rx="6" fill="#d8e3d5"/><rect x="42" y="12" width="36" height="34" rx="4" fill="#eef1df"/><rect x="42" y="49" width="36" height="17" rx="4" fill="#eef1df"/><rect x="70" y="25" width="3" height="14" rx="2" fill="#536b62"/></svg>`;case'prep':return `<svg ${common}><ellipse cx="60" cy="70" rx="40" ry="4" fill="#173b3520"/><rect x="21" y="25" width="78" height="9" rx="3" fill="#efe7d3"/><rect x="25" y="34" width="70" height="31" rx="4" fill="#789581"/><rect x="35" y="18" width="32" height="5" rx="2" fill="#bd8e59"/><rect x="72" y="18" width="18" height="4" rx="2" fill="#536b62"/></svg>`;case'stove':return `<svg ${common}><ellipse cx="60" cy="70" rx="37" ry="4" fill="#173b3520"/><rect x="27" y="27" width="66" height="38" rx="5" fill="#d1d9cf"/><rect x="24" y="21" width="72" height="10" rx="3" fill="#384d46"/><circle cx="44" cy="26" r="7" fill="#182f2a"/><circle cx="76" cy="26" r="7" fill="#182f2a"/><rect x="37" y="39" width="46" height="18" rx="3" fill="#344d45"/></svg>`;default:return'';}}
const fresh=()=>({version:1,money:900,owned:false,day:1,open:false,closing:false,elapsed:0,spawn:2,stock:6,hand:'',furniture:[],clients:[],nextId:1,served:0,lost:0,revenue:0,expense:0,totalServed:0,rating:100,cook:0,cookReady:false,pos:{x:1.9,z:8,yaw:0,pitch:-.21}});
let S=fresh(),loaded=false,storageOK=true,resetting=false;try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===1&&Array.isArray(raw.furniture)&&Number.isFinite(raw.money)){S=raw;loaded=true;}}catch(e){storageOK=false;}
let paused=true,buildMode=false,placing=null,ghost=null,target=null,job=null,toastTime=0,autoSave=0,uiTime=0,yaw=S.pos.yaw,pitch=S.pos.pitch,idleHintUntil=0,idleHintStarted=false;const keys={},joy={x:0,y:0};
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7d5d1');scene.fog=new THREE.Fog('#b7d5d1',23,65);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.06,80);camera.rotation.order='YXZ';camera.position.set(S.pos.x,1.65,S.pos.z);camera.rotation.set(pitch,yaw,0);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('panel').innerHTML='<h2>La 3D est indisponible</h2><p>Ouvre ce jeu dans Safari ou Chrome avec WebGL activé.</p>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;
scene.add(new THREE.HemisphereLight('#fff5d9','#769891',2.2));const sun=new THREE.DirectionalLight('#fff2d2',2.6);sun.position.set(-6,12,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12});sun.shadow.bias=-.002;scene.add(sun);
const mats={};function mat(c){return mats[c]||(mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.8}));}
function box(g,w,h,d,x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function cyl(g,r,h,x,y,z,c,r2=r){const m=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,12),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function sphere(g,r,x,y,z,c,seg=10){const m=new THREE.Mesh(new THREE.SphereGeometry(r,seg,Math.max(6,seg-2)),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function makeLimb(parent,x,y,z,upperLen,lowerLen,width,upperColor,lowerColor=upperColor){const upper=new THREE.Group();upper.position.set(x,y,z);parent.add(upper);box(upper,width,upperLen,width,0,-upperLen/2,0,upperColor);const lower=new THREE.Group();lower.position.y=-upperLen;upper.add(lower);box(lower,width*.9,lowerLen,width*.9,0,-lowerLen/2,0,lowerColor);return{upper,lower};}
function clearGroup(g){while(g.children.length){const c=g.children.pop();c.traverse?.(m=>{if(m.geometry)m.geometry.dispose();if(m.material&&m.material.userData?.temporary)m.material.dispose();});}}
function foodModel(kind='meal'){
  const g=new THREE.Group();
  if(kind==='ingredients'){
    box(g,.38,.035,.28,0,0,0,'#d4a56c');
    cyl(g,.075,.045,-.1,.055,-.02,'#7d4435');
    sphere(g,.055,.1,.065,-.04,'#cc5e45',8);
    box(g,.14,.018,.1,.06,.045,.08,'#6f9b58');
    cyl(g,.075,.04,-.1,.07,.08,'#e4bb72');
  }else if(kind==='prepared'){
    cyl(g,.2,.018,0,0,0,'#f4ead7');
    cyl(g,.11,.035,-.07,.045,0,'#8c5540');
    cyl(g,.12,.035,.08,.05,.02,'#dfb36d');
    box(g,.16,.018,.1,0,.07,-.08,'#6f9b58');
  }else if(kind==='cooked'){
    cyl(g,.2,.018,0,0,0,'#f4ead7');
    cyl(g,.115,.05,0,.055,0,'#6c392d');
    box(g,.16,.018,.1,0,.09,-.02,'#6f9b58');
  }else{
    const plate=cyl(g,.22,.018,0,0,0,'#f4ead7');
    const burger=new THREE.Group();g.add(burger);burger.position.y=.02;
    cyl(burger,.145,.055,0,.03,0,'#d9a45e',.11);
    box(burger,.17,.022,.14,0,.072,0,'#75a457');
    cyl(burger,.125,.045,0,.102,0,'#6a382c');
    box(burger,.17,.018,.14,0,.132,0,'#e5c150');
    cyl(burger,.15,.07,0,.17,0,'#dfa85f',.105);
    sphere(burger,.012,-.05,.205,-.055,'#f5e5b0',6);sphere(burger,.012,.04,.208,.025,'#f5e5b0',6);sphere(burger,.01,.075,.202,-.035,'#f5e5b0',6);
    g.userData.burger=burger;g.userData.plate=plate;
  }
  return g;
}
function label(g,text,x,y,z,w=2,h=.5,bg='#21483c',fg='#f7f0d5'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=fg;ctx.font='bold 48px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,66);const tx=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tx,side:THREE.DoubleSide}));m.position.set(x,y,z);g.add(m);return m;}
const world=new THREE.Group();scene.add(world);
box(world,80,.2,80,0,-.2,0,'#87a89b');box(world,24,.1,7,0,-.06,8,'#cecfc0');box(world,30,.04,4,0,-.08,13,'#7c8c87');for(let x=-12;x<13;x+=4)box(world,1.5,.02,.09,x,-.05,13,'#e9e2c7');
box(world,10,.16,10,0,-.09,-1,'#dbc5a0');box(world,10.3,.18,10.3,0,3.65,-1,'#eee4cd');for(let x=-5;x<5;x+=1)for(let z=-6;z<4;z+=1)box(world,.985,.02,.985,x+.5,.005,z+.5,(Math.round(x+z)%2)?'#e3d4ba':'#ecdfc8');
box(world,.22,3.6,10,-5,1.8,-1,'#ebdfc6');box(world,.22,3.6,10,5,1.8,-1,'#ebdfc6');box(world,10,3.6,.2,0,1.8,-6,'#bac8a6');
box(world,3.6,1.1,.2,-3.2,.55,4,'#385d4b');box(world,3.6,1.1,.2,3.2,.55,4,'#385d4b');box(world,10,.7,.28,0,3.3,4,'#365d4b');for(let x of [-5,-1.4,1.4,5])box(world,.15,3.3,.3,x,1.65,4,'#365d4b');
const glassmat=new THREE.MeshStandardMaterial({color:'#bde4d9',transparent:true,opacity:.16,roughness:.2});for(let x of [-3.2,3.2]){const m=box(world,3.4,1.8,.04,x,2,4,'#dcebe0');m.material=glassmat;box(world,3.6,.08,.4,x,1.13,4,'#eee7cf');}
box(world,10.5,.2,1.3,0,3.75,4.2,'#e5ba7c');for(let x=-5;x<5;x+=.6)box(world,.3,.03,1.3,x,3.87,4.2,'#f8eacc');label(world,'À  T A B L E',0,3.32,4.17,3,.45);
for(let z of [-5.85]){box(world,9.8,.12,.12,0,1.05,z,'#6c886d');box(world,9.8,.7,.08,0,.4,z,'#75906f');}for(let x of [-4.86,4.86])box(world,.1,.8,9.7,x,.4,-1,'#75906f');
for(let x of [-2.7,2.7]){cyl(world,.04,.5,x,3.1,-2,'#2f4941');cyl(world,.5,.2,x,2.8,-2,'#d6a25d',.18);const l=new THREE.PointLight('#ffe0a7',7,7,2);l.position.set(x,2.6,-2);scene.add(l);}
for(let x of [-5.8,5.8]){cyl(world,.38,.7,x,.35,4.5,'#b97955',.5);for(let i=0;i<4;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.5,0),mat(i%2?'#719369':'#547b59'));m.position.set(x+Math.sin(i)*.2,.95+i*.2,4.5+Math.cos(i)*.15);world.add(m);}}
for(let x of [-11,11]){box(world,6,7,8,x,3.5,-2,'#c8bdab');box(world,6,.2,8.5,x,7,-2,'#71837b');for(let y of [2,4.5])for(let a of [-1.5,1.5])box(world,1.1,1.6,.05,x+a,y,2.05,'#7d9e98');}
// V1.3 : petits détails architecturaux légers pour casser l'effet "pièce vide".
box(world,9.7,.11,.07,0,.08,-5.84,'#738b70');box(world,.07,.11,9.6,-4.86,.08,-1,'#738b70');box(world,.07,.11,9.6,4.86,.08,-1,'#738b70');
box(world,2.15,1.08,.055,2.3,2.03,-5.83,'#28483d');label(world,'MENU',2.3,2.22,-5.795,1.35,.22,'#28483d','#eef1d3');box(world,1.45,.045,.08,2.3,1.58,-5.77,'#d7b376');
const wallDecor=new THREE.Group();wallDecor.position.set(-4.82,1.85,-2.7);wallDecor.rotation.y=Math.PI/2;box(wallDecor,1.2,.75,.05,0,0,0,'#e8dfc9');box(wallDecor,1.05,.6,.06,0,0,-.02,'#789581');box(wallDecor,.48,.055,.07,0,.18,-.06,'#e5ba7c');scene.add(wallDecor);
const sign=new THREE.Group();sign.position.set(1.9,0,5.15);box(sign,.08,1.35,.1,-.42,.68,0,'#936e49');box(sign,.08,1.35,.1,.42,.68,0,'#936e49');box(sign,1.05,.95,.15,0,1,0,'#c89b67');let signText=label(sign,'À VENDRE',0,1.05,.09,.95,.32);scene.add(sign);sign.userData.kind='sign';const backSign=label(sign,'À VENDRE',0,1.05,-.09,.95,.32);backSign.rotation.y=Math.PI;
const furnitureMeshes=new Map(),clientMeshes=new Map();
function dispose(g){g.traverse(m=>{if(m.geometry)m.geometry.dispose();if(m.material?.map){m.material.map.dispose();m.material.dispose();}});g.removeFromParent();}
function furnitureMesh(f){
const g=new THREE.Group(),wood='#bd8e59',woodDark='#9d744c',metal='#536b62',metalDark='#334b43',green='#719478',cream='#efe7d3';
switch(f.type){
case'table':{
  box(g,1.34,.09,1.12,0,.84,0,wood);box(g,1.18,.08,.96,0,.78,0,woodDark);
  for(let x of [-.5,.5])for(let z of [-.4,.4]){box(g,.07,.75,.07,x,.39,z,metalDark);box(g,.11,.025,.11,x,.03,z,metal);}
  cyl(g,.075,.12,0,.94,0,'#f0e1bf');sphere(g,.035,0,1.02,0,'#d6a25d',8);break;}
case'chair':{
  box(g,.54,.085,.52,0,.48,0,metalDark);box(g,.48,.085,.46,0,.53,0,green);
  box(g,.5,.08,.08,0,.89,.23,green);box(g,.47,.38,.065,0,.72,.24,green);
  for(let x of [-.2,.2])for(let z of [-.2,.2])box(g,.045,.45,.045,x,.25,z,metalDark);
  break;}
case'fridge':{
  box(g,.88,1.92,.82,0,.96,0,'#cbd8cf');box(g,.82,1.84,.045,0,.96,.43,'#eaf0e4');
  box(g,.78,1.05,.035,0,.68,.455,'#f1f3e8');box(g,.78,.58,.035,0,1.55,.455,'#eef2e5');
  box(g,.035,.37,.045,.3,.82,.49,metalDark);box(g,.035,.24,.045,.3,1.48,.49,metalDark);
  box(g,.88,.035,.83,0,.02,0,metalDark);for(let x of [-.31,.31])box(g,.09,.06,.09,x,.03,.27,metalDark);
  label(g,'FRAIS',0,1.63,.485,.5,.11,'#789581','#f4f4df');break;}
case'prep':{
  box(g,1.42,.78,.74,0,.42,0,'#789581');box(g,1.5,.075,.82,0,.86,0,cream);box(g,1.34,.035,.04,0,.72,.385,'#5f786b');
  box(g,.58,.44,.035,-.35,.43,.39,'#6f8b79');box(g,.58,.44,.035,.35,.43,.39,'#6f8b79');
  for(let y of [.63,.48,.33])box(g,.18,.025,.025,.35,y,.415,metalDark);
  box(g,.55,.025,.34,-.18,.915,-.03,wood);box(g,.22,.025,.06,.37,.918,.1,metalDark);
  const prepIngredients=foodModel('ingredients');prepIngredients.position.set(-.18,.955,-.02);prepIngredients.scale.set(.72,.72,.72);prepIngredients.visible=false;g.add(prepIngredients);
  const prepCooked=foodModel('cooked');prepCooked.position.set(-.18,.955,-.02);prepCooked.scale.set(.72,.72,.72);prepCooked.visible=false;g.add(prepCooked);
  g.userData.prepIngredients=prepIngredients;g.userData.prepCooked=prepCooked;break;}
case'stove':{
  box(g,1.02,.82,.8,0,.43,0,'#cbd4cc');box(g,1.08,.06,.86,0,.87,0,metalDark);
  box(g,.76,.38,.035,0,.42,.415,'#243c36');box(g,.64,.27,.02,0,.42,.438,'#4c635a');box(g,.72,.035,.045,0,.66,.44,metalDark);
  for(let x of [-.3,0,.3]){cyl(g,.04,.045,x,.74,.43,'#c49658');cyl(g,.016,.052,x,.765,.43,'#263d36');}
  for(let x of [-.25,.25])for(let z of [-.2,.2]){cyl(g,.145,.018,x,.915,z,'#182f2a');cyl(g,.085,.021,x,.928,z,'#354b43');}
  const pan=new THREE.Group();cyl(pan,.18,.035,0,0,0,'#263d36');box(pan,.22,.035,.055,.27,.005,0,'#263d36');pan.position.set(-.24,.95,-.18);g.add(pan);
  const cookRaw=cyl(pan,.11,.028,0,.035,0,'#8b4b3d');const cookDone=cyl(pan,.11,.03,0,.036,0,'#66372d');cookRaw.visible=false;cookDone.visible=false;g.userData.cookRaw=cookRaw;g.userData.cookDone=cookDone;break;}
case'till':{
  box(g,1.02,.88,.7,0,.45,0,woodDark);box(g,1.08,.07,.76,0,.93,0,cream);box(g,.92,.46,.035,0,.52,.37,wood);
  box(g,.42,.08,.3,0,1.0,0,metal);const screen=box(g,.42,.3,.055,0,1.18,-.055,metalDark);screen.rotation.x=-.22;
  box(g,.32,.025,.18,0,1.065,-.21,'#d9dfcf');for(let x of [-.1,0,.1])for(let z of [-.04,.04])box(g,.035,.018,.03,x,1.085,z-.2,'#789581');
  label(g,'€',0,1.2,-.018,.16,.16,'#27493f','#ddecaa');box(g,.22,.018,.1,.31,.98,-.12,'#f7f1dc');break;}
}
g.position.set(f.x,0,f.z);g.rotation.y=f.rot||0;g.userData.kind='furniture';g.userData.id=f.id;return g;}
function syncFurniture(){for(const g of furnitureMeshes.values())dispose(g);furnitureMeshes.clear();for(const f of S.furniture){const g=furnitureMesh(f);scene.add(g);furnitureMeshes.set(f.id,g);}}
function person(c){
const g=new THREE.Group(),body=new THREE.Group();g.add(body);
const shirts=['#b37556','#5b8588','#a8945d','#977a99','#587861','#c17e5f','#6b728f','#8a725d'],pants=['#354d50','#32423c','#4f4640','#3f4654'],skins=['#e0b18c','#c98f68','#f0c6a0','#9f694b'],hairs=['#524638','#342d28','#806044','#272a28'];
const idx=(c.id||1)-1,shirt=shirts[idx%shirts.length],skin=skins[(idx*3)%skins.length],hair=hairs[(idx*5)%hairs.length],pant=pants[(idx*7)%pants.length];
// Torse légèrement conique, cou et tête low-poly.
cyl(body,.205,.54,0,1.03,0,shirt,.27);cyl(body,.09,.1,0,1.34,0,skin);const head=sphere(body,.205,0,1.5,0,skin,10);head.scale.set(.96,1.05,.92);
// Visage minimaliste mais lisible en jeu.
sphere(body,.018,-.065,1.52,-.185,'#26352f',6);sphere(body,.018,.065,1.52,-.185,'#26352f',6);box(body,.055,.012,.012,0,1.435,-.192,'#8d5f4e');sphere(body,.018,0,1.485,-.205,skin,6);
// Coiffures variées.
if(idx%4===0){const h=sphere(body,.212,0,1.61,.015,hair,9);h.scale.y=.58;box(body,.11,.11,.12,-.13,1.55,.08,hair);}
else if(idx%4===1){cyl(body,.21,.11,0,1.64,.01,hair);box(body,.12,.15,.08,.14,1.55,.08,hair);}
else if(idx%4===2){box(body,.34,.1,.3,0,1.65,.02,hair);box(body,.07,.22,.08,-.16,1.56,.05,hair);box(body,.07,.2,.08,.16,1.57,.05,hair);}
else{const h=sphere(body,.215,0,1.61,.01,hair,8);h.scale.set(1,.48,.95);for(let x of [-.13,-.045,.045,.13])sphere(body,.055,x,1.6,.04,hair,7);}
// Bras et jambes segmentés pour de vraies animations de marche/assis.
const armL=makeLimb(body,-.27,1.21,0,.28,.26,.095,shirt,skin),armR=makeLimb(body,.27,1.21,0,.28,.26,.095,shirt,skin);
const legL=makeLimb(body,-.12,.79,0,.42,.41,.12,pant,pant),legR=makeLimb(body,.12,.79,0,.42,.41,.12,pant,pant);
box(legL.lower,.16,.08,.25,0,-.43,-.06,'#263d36');box(legR.lower,.16,.08,.25,0,-.43,-.06,'#263d36');
// Assiette/burger posé devant le client pendant le repas.
const meal=foodModel('meal');meal.position.set(0,.84,-.48);meal.scale.set(.75,.75,.75);meal.visible=false;g.add(meal);
g.userData={kind:'client',id:c.id,body,head,armL,armR,legL,legR,meal,mealBurger:meal.userData.burger,pose:0};scene.add(g);return g;}
function dims(f,pad=0){let d=catalog[f.type],swap=Math.abs(Math.sin(f.rot||0))>.5;return {w:(swap?d.d:d.w)/2+pad,d:(swap?d.w:d.d)/2+pad};}
function insideFurniture(x,z,f,pad=.22){const d=dims(f,pad);return Math.abs(x-f.x)<d.w&&Math.abs(z-f.z)<d.d;}
function blocked(x,z,ignore=null,list=S.furniture,pad=.23){if(x< -4.65||x>4.65||z< -5.65||z>9.5)return true;if(Math.abs(z-4)<.35&&Math.abs(x)>1.1)return true;if(!S.owned&&z<4.4)return true;return list.some(f=>f.id!==ignore&&insideFurniture(x,z,f,pad));}
// Navigation grid includes the entrance and street. Furniture remains an obstacle.
function route(start,end,ignore=null,list=S.furniture){const step=.4;const gx=x=>Math.round((x+4.4)/step),gz=z=>Math.round((z+5.4)/step),point=(x,z)=>({x:x*step-4.4,z:z*step-5.4});const sx=gx(start.x),sz=gz(start.z),tx=gx(end.x),tz=gz(end.z);const id=(x,z)=>x+','+z,queue=[[sx,sz]],parents=new Map([[id(sx,sz),null]]);let found=null;for(let i=0;i<queue.length&&i<2500;i++){const [x,z]=queue[i];if(Math.hypot(x-tx,z-tz)<=1){found=[x,z];break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,nz=z+dz,k=id(nx,nz),p=point(nx,nz);if(parents.has(k)||blocked(p.x,p.z,ignore,list,.17))continue;parents.set(k,[x,z]);queue.push([nx,nz]);}}if(!found)return null;const out=[];let cur=found;while(cur){out.push(point(...cur));cur=parents.get(id(...cur));}return out.reverse();}
function chairs(){return S.furniture.filter(f=>f.type==='chair'&&S.furniture.some(t=>t.type==='table'&&Math.hypot(t.x-f.x,t.z-f.z)<1.7));}
function seatSpot(f){return{x:f.x,z:f.z};}
function ready(){const need=['table','chair','till','fridge','prep','stove'];return need.every(t=>S.furniture.some(f=>f.type===t))&&S.furniture.filter(f=>f.type==='chair').length>=2&&chairs().filter(c=>route({x:0,z:5},seatSpot(c),c.id)).length>=2;}
function save(){if(resetting)return;S.pos={x:camera.position.x,z:camera.position.z,yaw,pitch};try{localStorage.setItem(KEY,JSON.stringify(S));storageOK=true;}catch{storageOK=false;} }
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;toastTime=3.5;}
function modal(html,mode=''){paused=true;joy.x=joy.y=0;Object.keys(keys).forEach(k=>keys[k]=false);$('modal').hidden=false;const panel=$('panel');panel.className=mode;panel.innerHTML=html;document.exitPointerLock?.();}
function resume(){paused=false;$('modal').hidden=true;if(!idleHintStarted){idleHintStarted=true;idleHintUntil=performance.now()+6500;}}
function showWelcome(){modal(`<div class="eyebrow">SIMULATEUR DE RESTAURANT · V1.3</div><h1>Une adresse.<br>Votre histoire.</h1><p>Un local vide, quelques économies et votre premier service à inventer.</p><div class="tags"><span>3D · Première personne</span><span>Sauvegarde locale</span></div><p><b>Déplacez-vous à gauche.</b> Glissez à droite pour regarder. Visez un objet, puis touchez le bouton d’action.</p><button class="primary" id="start">${loaded?'Reprendre mon restaurant':'Commencer l’aventure'}</button><button class="secondary" id="welcomeHelp">Voir les commandes</button>`);$('start').onclick=()=>{resume();if(!storageOK)toast('Sauvegarde indisponible dans ce navigateur.');};$('welcomeHelp').onclick=showHelp;}
function showHelp(){modal(`<div class="eyebrow">LE CARNET DU CHEF</div><h2>Votre premier service</h2><ol class="steps"><li>Achetez le local : <b>250 €</b>, sur la pancarte devant.</li><li>Entrez, puis ouvrez <b>Aménager</b>. Achetez chaque équipement et deux chaises.</li><li>Placez les chaises près de la table. Laissez des passages et la porte libres.</li><li>Ouvrez avec la pancarte. Prenez la commande du client.</li><li>Réfrigérateur → ingrédients. Plan de travail → préparer. Plaque → cuire. Plan de travail → dresser.</li><li>Servez le client, puis encaissez à la caisse après son repas.</li></ol><p>Un burger : <b>18 € + pourboire</b>. 6 portions offertes ; réassort de 6 portions à 18 €. Un service dure 4 minutes, puis finit après le départ des clients.</p><p>Mobile : joystick à gauche, vue à droite. Ordinateur : ZQSD / WASD / flèches, glisser la souris pour regarder, E pour agir, R pour pivoter. La pause arrête les clients et la cuisson.</p><button class="primary" id="back">C’est parti</button>`);$('back').onclick=resume;}
function showShop(){if(!S.owned)return toast('Achetez d’abord le local sur la pancarte.');if(S.open||S.clients.length||S.closing)return toast('Aménagez entre deux journées, sans client.');if(job)return;buildMode=true;const st=setupState();const req=[['table',1],['chair',2],['till',1],['fridge',1],['prep',1],['stove',1]],done=req.filter(([t,n])=>st.counts[t]>=n).length;modal(`<div class="marketHead"><div><div class="eyebrow">MARKET</div><h2>Aménagement</h2></div><div class="marketMoney">${S.money} €</div></div><div class="marketStatus ${done===6?'ready':''}">${done===6?'✓ Restaurant prêt':done+'/6 équipements essentiels'}</div><div class="marketShop">${Object.entries(catalog).map(([type,d])=>{const count=S.furniture.filter(f=>f.type===type).length;return `<button class="marketItem" data-buy="${type}" ${S.money<d.price?'disabled':''}><span class="marketVisual">${marketIcon(type)}</span><span class="marketInfo"><b>${d.name}</b><small>${count} installé${count>1?'s':''}</small></span><em>${d.price} €</em></button>`;}).join('')}</div><div class="marketFooter"><button class="marketMove" id="arrange">Déplacer</button><button class="marketClose" id="shopClose">Fermer</button></div>`,'marketPanel');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>beginPlacement(b.dataset.buy));$('arrange').onclick=resume;$('shopClose').onclick=()=>{buildMode=false;resume();};}
function beginPlacement(type,id=null){const f=S.furniture.find(f=>f.id===id);placing={type,id,rot:f?.rot||0,x:f?.x||0,z:f?.z||0,valid:false};if(id)furnitureMeshes.get(id).visible=false;ghost=furnitureMesh({...placing,id:-1});ghost.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.transparent=true;m.material.opacity=.5;}});scene.add(ghost);$('placement').hidden=false;$('sell').hidden=!id;resume();}
function endPlacement(){if(placing?.id)furnitureMeshes.get(placing.id).visible=true;if(ghost){ghost.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose();}});scene.remove(ghost);}placing=null;ghost=null;$('placement').hidden=true;}
function validPlacement(f){const d=dims(f,.1);if(Math.abs(f.x)+d.w>4.8||f.z-d.d< -5.8||f.z+d.d>3.75)return false;if(Math.abs(f.x)<1.35+d.w&&f.z+d.d>2.9)return false;if(S.furniture.some(o=>{if(o.id===f.id)return false;let a=dims(f,.07),b=dims(o);return Math.abs(f.x-o.x)<a.w+b.w&&Math.abs(f.z-o.z)<a.d+b.d;}))return false;if(insideFurniture(camera.position.x,camera.position.z,f,.25))return false;const list=S.furniture.filter(o=>o.id!==f.id).concat(f);if(!route(camera.position,{x:0,z:5},null,list))return false;return true;}
function commitPlacement(){if(!placing?.valid)return toast('Position bloquée : libérez le passage ou reculez.');if(!placing.id&&S.money<catalog[placing.type].price)return toast('Budget insuffisant.');const f={id:placing.id||S.nextId++,type:placing.type,x:placing.x,z:placing.z,rot:placing.rot};if(placing.id)S.furniture=S.furniture.map(o=>o.id===f.id?f:o);else{S.money-=catalog[f.type].price;S.furniture.push(f);}endPlacement();syncFurniture();save();toast('Meuble installé. Visez-le pour le déplacer.');}
function timed(label,duration,done,stationId=null,visual=''){if(job)return;job={label,total:duration,left:duration,done,stationId,visual};$('progress').style.display='block';}
function signAction(){if(!S.owned){modal('<div class="eyebrow">VOTRE FUTURE ADRESSE</div><h2>Les clés sont à vous.</h2><p>Un local de 100 m² pour <b>250 €</b>. Il vous restera <b>650 €</b> pour l’équiper. Six portions sont offertes à l’ouverture.</p><button class="primary" id="buyLocal">Acheter · 250 €</button><button class="secondary" id="noBuy">Plus tard</button>');$('buyLocal').onclick=()=>{if(S.money<250)return;S.money-=250;S.owned=true;resume();save();toast('Bienvenue chez vous ! Entrez par la porte centrale.');};$('noBuy').onclick=resume;return;}if(S.open){S.open=false;S.closing=true;toast('Dernières commandes : terminez le service en cours.');save();return;}if(S.closing)return toast('Servez et encaissez les derniers clients.');if(!ready())return toast('Il faut tous les équipements, deux chaises près d’une table et des passages accessibles.');buildMode=false;S.open=true;S.elapsed=0;S.spawn=1;S.revenue=0;S.expense=0;S.served=0;S.lost=0;save();toast('Jour '+S.day+' · Votre restaurant est ouvert !');}
function interact(){if(paused||placing||job)return;if(!target)return;const kind=target.userData.kind;if(kind==='sign'){signAction();return;}if(kind==='client'){const c=S.clients.find(c=>c.id===target.userData.id);if(!c)return;if(c.state==='order'){c.state='wait';toast('Commande : un burger maison.');save();}else if(c.state==='wait'&&S.hand==='meal'){S.hand='';c.state='eat';c.timer=0;c.satisfaction=Math.max(20,Math.round(c.patience/100*100));toast('Bon appétit !');save();}else toast(c.state==='pay'?'Encaissez à la caisse.':'Ce client attend '+(c.state==='wait'?'son burger.':'un instant.'));return;}
const f=S.furniture.find(f=>f.id===target.userData.id);if(!f)return;if(buildMode){beginPlacement(f.type,f.id);return;}switch(f.type){case'fridge':if(S.hand)return toast('Terminez d’abord ce que vous avez en main.');if(!S.stock){if(S.money<18)return toast('Réassort : 18 € nécessaires.');modal('<h2>Remplir le réfrigérateur</h2><p>6 portions de pain, légumes et steak pour 18 €.</p><button class="primary" id="restock">Acheter · 18 €</button><button class="secondary" id="restockCancel">Retour</button>');$('restock').onclick=()=>{if(S.money>=18){S.money-=18;S.stock+=6;S.expense+=18;}resume();save();};$('restockCancel').onclick=resume;}else{S.stock--;S.hand='ingredients';save();toast('Pain, légumes et steak récupérés.');}break;case'prep':if(S.hand==='ingredients')timed('Préparation des ingrédients',2,()=>{S.hand='prepared';toast('Prêt pour la cuisson.');},f.id,'ingredients');else if(S.hand==='cooked')timed('Dressage du burger',1.5,()=>{S.hand='meal';toast('Burger prêt à servir !');},f.id,'cooked');else toast('Apportez les ingrédients, ou le burger cuit à dresser.');break;case'stove':if(S.cookReady){if(S.hand)return toast('Il faut les mains libres.');S.cookReady=false;S.hand='cooked';save();toast('Cuisson terminée. Dressez sur le plan de travail.');}else if(S.cook>0)toast('Cuisson : encore '+Math.ceil(S.cook)+' s.');else if(S.hand==='prepared'){S.hand='';S.cook=5;save();toast('Cuisson lancée · 5 secondes.');}else toast('Préparez les ingrédients sur le plan de travail.');break;case'till':{const c=S.clients.find(c=>c.state==='pay');if(!c)return toast('Aucun paiement en attente.');const tip=Math.round(c.satisfaction/100*6),cash=18+tip;S.money+=cash;S.revenue+=cash;S.served++;S.totalServed++;S.rating=Math.round((S.rating*4+c.satisfaction)/5);leave(c);save();toast('+'+cash+' € · dont '+tip+' € de pourboire !');break;}default:toast('Installez les chaises près des tables.');}}
function leave(c){c.state='leave';c.path=route(c,{x:0,z:8.5},c.chair)||[{x:0,z:4.5},{x:0,z:8.5}];c.pathIndex=0;c.timer=0;}
function spawnClient(){const available=chairs().filter(f=>!S.clients.some(c=>c.chair===f.id&&c.state!=='leave'));for(const chair of available){const path=route({x:0,z:8.5},seatSpot(chair),chair.id);if(!path)continue;const c={id:S.nextId++,chair:chair.id,x:0,z:8.5,state:'walk',path:path.concat([seatSpot(chair)]),pathIndex:0,patience:100,timer:0,satisfaction:100};S.clients.push(c);return true;}return false;}
function finishDay(){S.closing=false;const day=S.day;S.day++;save();modal(`<div class="eyebrow">SERVICE TERMINÉ · JOUR ${day}</div><h2>Une journée bien remplie.</h2><div class="stats"><div><b>${S.served}</b><small>CLIENTS SERVIS</small></div><div><b>${S.revenue-S.expense} €</b><small>SOLDE DU SERVICE*</small></div></div><p>${S.lost?S.lost+' client(s) sont partis avant le repas.':'Vous avez pris soin de chaque client.'}<br>Satisfaction moyenne : ${S.rating} %.</p><p>*Encaissements moins réassorts achetés pendant ce service. Les portions offertes ne sont pas facturées.</p><button class="primary" id="nextDay">Préparer le jour ${S.day}</button>`);$('nextDay').onclick=resume;}
function updateClients(dt){if(S.open){S.elapsed+=dt;S.spawn-=dt;if(S.spawn<=0){spawnClient();S.spawn=S.totalServed<2?20:13;}if(S.elapsed>=240){S.open=false;S.closing=true;toast('Le service se termine. Occupez-vous des derniers clients.');}}
for(const c of [...S.clients]){c.timer+=dt;if(c.state==='walk'||c.state==='leave'){const p=c.path[c.pathIndex];if(p){const dx=p.x-c.x,dz=p.z-c.z,dist=Math.hypot(dx,dz),speed=dt*1.1;if(dist<speed){c.x=p.x;c.z=p.z;c.pathIndex++;}else{c.x+=dx/dist*speed;c.z+=dz/dist*speed;c.angle=Math.atan2(-dx,-dz);}}else if(c.state==='leave'){S.clients=S.clients.filter(a=>a!==c);const g=clientMeshes.get(c.id);if(g)dispose(g);clientMeshes.delete(c.id);}else{c.state='order';c.timer=0;toast('Un client est prêt à commander.');}}
else if(c.state==='order'||c.state==='wait'){c.patience-=dt*(c.state==='order'?.32:.65);if(c.patience<=0){S.lost++;S.rating=Math.max(0,S.rating-8);leave(c);toast('Un client a perdu patience.');}}
else if(c.state==='eat'&&c.timer>=9){c.state='pay';c.timer=0;toast('Un client souhaite payer. Rendez-vous à la caisse.');}
}
if(S.closing&&!S.clients.length)finishDay();}
const ray=new THREE.Raycaster(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let pointerDown=null;
function pick(){target=null;ray.setFromCamera({x:0,y:0},camera);const objects=[sign,...furnitureMeshes.values(),...clientMeshes.values()];const hits=ray.intersectObjects([...objects,world],true);for(const h of hits){if(h.distance>3.2)break;let o=h.object;while(o.parent&&!o.userData.kind)o=o.parent;if(o.visible&&o.userData.kind){target=o;break;}else break;}}
function actionText(){if(!target)return[performance.now()<idleHintUntil?'Approchez-vous et visez un objet':'',''];const d=target.userData;if(d.kind==='sign')return[S.owned?'Pancarte du restaurant':'Local commercial',!S.owned?'Acheter · 250 €':S.open?'Fermer le service':S.closing?'Service en cours':'Ouvrir · Jour '+S.day];if(d.kind==='client'){const c=S.clients.find(c=>c.id===d.id);return[clientName(c)+' · '+Math.ceil(c?.patience||0)+' % de patience',c?.state==='order'?'Prendre la commande':c?.state==='wait'?(S.hand==='meal'?'Servir le burger':'Burger en attente'):c?.state==='pay'?'Paiement à la caisse':c?.state==='eat'?'Bon appétit':'Client en déplacement'];}const f=S.furniture.find(f=>f.id===d.id);if(!f)return['',''];if(buildMode)return[catalog[f.type].name,'Déplacer'];const names={fridge:S.stock?'Prendre les ingrédients':'Réassort · 18 €',prep:S.hand==='cooked'?'Dresser le burger':'Préparer les ingrédients',stove:S.cookReady?'Récupérer le burger':S.cook>0?'Cuisson · '+Math.ceil(S.cook)+' s':'Lancer la cuisson',till:'Encaisser',table:'Table bistro',chair:'Chaise'};return[catalog[f.type].name,names[f.type]];}
function goal(){if(!S.owned)return'Achetez le local sur la pancarte devant vous.';if(placing)return'Déplacez le viseur sur le sol, puis validez.';if(!ready()){const st=setupState();if(st.missing.length){const labels=st.missing.slice(0,2).map(([t,n])=>{const left=n-st.counts[t];return left+' '+setupLabels[t]+(left>1?'s':'');});return'Encore '+labels.join(' et ')+(st.missing.length>2?'…':'')+' à installer.';}return'Libérez un passage entre l’entrée, les chaises et les équipements.';}if(!S.open&&!S.closing)return'Votre restaurant est prêt. Ouvrez avec la pancarte.';if(S.clients.some(c=>c.state==='pay'))return'Un client veut payer. Encaissez à la caisse.';if(S.hand==='meal')return'Servez le burger au client qui attend.';if(S.hand==='cooked')return'Dressez le repas sur le plan de travail.';if(S.cookReady)return'La cuisson est terminée ! Récupérez le burger.';if(S.cook>0)return'La cuisson est en cours. Préparez le prochain service.';if(S.hand==='prepared')return'Apportez les ingrédients préparés à la plaque.';if(S.hand==='ingredients')return'Préparez les ingrédients sur le plan de travail.';if(S.clients.some(c=>c.state==='wait'))return'Récupérez une portion dans le réfrigérateur.';if(S.clients.some(c=>c.state==='order'))return'Approchez-vous du client pour prendre sa commande.';return'Accueillez vos clients. Votre bistrot prend vie.';}
let lastSign='';function ui(){ $('money').textContent=S.money+' €';$('day').textContent='JOUR '+S.day;$('goal').textContent=goal();let status=S.open?'Ouvert · '+Math.max(0,Math.ceil((240-S.elapsed)/60))+' min':S.closing?'Dernier service':S.owned?'Fermé · '+S.stock+' portions':'À vendre';if(S.cook>0)status+=' · Cuisson '+Math.ceil(S.cook)+' s';else if(S.cookReady)status+=' · Cuisson prête';$('statusText').textContent=status+(buildMode?' · Aménagement':'');$('status').querySelector('i').style.background=S.open?'#bde79b':'#f7c97d';const [title,act]=actionText();$('target').textContent=job?job.label:title;$('act').textContent=job?'En cours…':act||'';$('act').hidden=!job&&!act;$('act').disabled=!target||!!job;$('context').classList.toggle('idle',!target&&!job);$('context').hidden=!!placing;$('crosshair').classList.toggle('active',!!target&&!placing);const dp=$('dayProgress');dp.classList.toggle('show',S.open||S.closing);dp.firstElementChild.style.width=Math.min(100,(S.elapsed/240)*100)+'%';$('orders').innerHTML=S.clients.filter(c=>!['walk','leave'].includes(c.state)).slice(0,4).map(c=>`<div class="order"><strong>${c.state==='order'?'Une commande ?':c.state==='eat'?'Bon appétit !':c.state==='pay'?'Paiement en attente':'1 × Burger maison'}</strong><small>${clientName(c)} · ${c.state==='pay'?'Caisse':Math.ceil(c.patience)+' % de patience'}</small><div class="bar"><span style="width:${Math.max(0,c.patience)}%;background:${c.patience<30?'#c97452':'#488e65'}"></span></div></div>`).join('');const st=!S.owned?'À VENDRE':S.open?'OUVERT':'FERMÉ';if(lastSign!==st){for(const m of [signText,backSign]){const ctx=m.material.map.image.getContext('2d');ctx.fillStyle='#21483c';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f7f0d5';ctx.font='bold 48px sans-serif';ctx.textAlign='center';ctx.fillText(st,256,66);m.material.map.needsUpdate=true;}lastSign=st;}}
function syncFoodVisuals(){
  for(const f of S.furniture){const g=furnitureMeshes.get(f.id);if(!g)continue;
    if(f.type==='stove'){if(g.userData.cookRaw)g.userData.cookRaw.visible=S.cook>0;if(g.userData.cookDone)g.userData.cookDone.visible=!!S.cookReady;}
    if(f.type==='prep'){const active=job?.stationId===f.id;if(g.userData.prepIngredients)g.userData.prepIngredients.visible=!!(active&&job.visual==='ingredients');if(g.userData.prepCooked)g.userData.prepCooked.visible=!!(active&&job.visual==='cooked');}
  }
}
function updatePlacement(){ray.setFromCamera({x:0,y:-.18},camera);const p=new THREE.Vector3();if(!ray.ray.intersectPlane(floorPlane,p)||p.distanceTo(camera.position)>6){p.copy(camera.position);p.x-=Math.sin(yaw)*2.5;p.z-=Math.cos(yaw)*2.5;}placing.x=Math.round(p.x*10)/10;placing.z=Math.round(p.z*10)/10;placing.valid=validPlacement(placing);ghost.position.set(placing.x,.015,placing.z);ghost.rotation.y=placing.rot;ghost.traverse(m=>{if(m.isMesh)m.material.color.set(placing.valid?'#96daa2':'#e78065');});$('confirm').disabled=!placing.valid;$('placeHint').textContent=placing.valid?'Position libre · '+(placing.id?'Déplacement':catalog[placing.type].price+' €'):'Position bloquée · Visez un sol libre';}
const held=new THREE.Group(),heldFood=new THREE.Group();camera.add(held);scene.add(camera);held.position.set(0,-.42,-.72);held.rotation.x=-.08;held.add(heldFood);const foreL=box(held,.09,.34,.1,-.29,-.15,.12,'#e0b18c'),foreR=box(held,.09,.34,.1,.29,-.15,.12,'#e0b18c');foreL.rotation.z=-.38;foreR.rotation.z=.38;sphere(held,.075,-.23,-.005,.03,'#e0b18c',8);sphere(held,.075,.23,-.005,.03,'#e0b18c',8);let lastHeld='__';
function syncHeld(){const key=S.hand+'|'+(job?.visual||'');if(lastHeld===key)return;lastHeld=key;clearGroup(heldFood);if(!S.hand||job?.visual){held.visible=false;return;}const m=foodModel(S.hand);m.scale.set(.9,.9,.9);heldFood.add(m);held.visible=true;}
held.visible=false;
let previous=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-previous)/1000,.05);previous=now;if(!paused&&!document.hidden){let forward=(keys.KeyW||keys.KeyZ||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-joy.y,side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.KeyQ||keys.ArrowLeft?1:0)+joy.x;let n=Math.max(1,Math.hypot(forward,side));forward/=n;side/=n;let dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*dt*2.6,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*dt*2.6;if(!blocked(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!blocked(camera.position.x,camera.position.z+dz))camera.position.z+=dz;camera.rotation.set(pitch,yaw,0);if(placing)updatePlacement();else pick();if(job){job.left-=dt;$('progress').firstElementChild.style.width=(1-job.left/job.total)*100+'%';if(job.left<=0){job.done();job=null;$('progress').style.display='none';save();}}if(S.cook>0){S.cook=Math.max(0,S.cook-dt);if(!S.cook){S.cookReady=true;toast('Le burger est cuit !');save();}}updateClients(dt);autoSave+=dt;if(autoSave>4){save();autoSave=0;}toastTime-=dt;if(toastTime<0)$('toast').style.opacity=0;}
for(const c of S.clients){let g=clientMeshes.get(c.id);if(!g){g=person(c);clientMeshes.set(c.id,g);}const u=g.userData,seated=['order','wait','eat','pay'].includes(c.state),moving=['walk','leave'].includes(c.state),phase=now*.008+c.id*.9,swing=Math.sin(phase);
  g.position.set(c.x,moving?Math.abs(Math.sin(phase*2))*.022:0,c.z);u.pose+=( (seated?1:0)-u.pose)*Math.min(1,dt*7);u.body.position.y=-.22*u.pose;u.body.rotation.z=moving?swing*.022:0;
  if(moving){u.armL.upper.rotation.x=swing*.58;u.armR.upper.rotation.x=-swing*.58;u.armL.lower.rotation.x=Math.max(0,-swing)*.22;u.armR.lower.rotation.x=Math.max(0,swing)*.22;u.legL.upper.rotation.x=-swing*.5;u.legR.upper.rotation.x=swing*.5;u.legL.lower.rotation.x=Math.max(0,swing)*.28;u.legR.lower.rotation.x=Math.max(0,-swing)*.28;u.head.rotation.y=swing*.035;}
  else if(seated){u.legL.upper.rotation.x=1.2;u.legR.upper.rotation.x=1.2;u.legL.lower.rotation.x=-1.18;u.legR.lower.rotation.x=-1.18;const eat=c.state==='eat',waitBob=Math.sin(now*.004+c.id)*.035;u.armL.upper.rotation.x=eat ? .38+Math.sin(now*.011+c.id)*.28 : .06+waitBob;u.armR.upper.rotation.x=eat ? .46-Math.sin(now*.011+c.id)*.24 : .02-waitBob;u.armL.lower.rotation.x=eat?-.65:0;u.armR.lower.rotation.x=eat?-.72:0;u.head.rotation.y=Math.sin(now*.0025+c.id)*.05;}
  else{u.armL.upper.rotation.x=u.armR.upper.rotation.x=u.armL.lower.rotation.x=u.armR.lower.rotation.x=0;u.legL.upper.rotation.x=u.legR.upper.rotation.x=u.legL.lower.rotation.x=u.legR.lower.rotation.x=0;}
  u.meal.visible=c.state==='eat'||c.state==='pay';if(u.mealBurger){u.mealBurger.visible=c.state==='eat';if(c.state==='eat'){const k=Math.max(.25,1-c.timer/12);u.mealBurger.scale.set(k,k,k);}else u.mealBurger.scale.set(1,1,1);}
  const chair=S.furniture.find(f=>f.id===c.chair);g.rotation.y=moving?c.angle||0:chair?.rot||0;}
syncFoodVisuals();syncHeld();held.rotation.z=Math.sin(now*.003)*.02;held.position.y=-.42+Math.sin(now*.004)*.008;uiTime+=dt;if(uiTime>.15){ui();uiTime=0;}renderer.render(scene,camera);}
$('act').onclick=interact;$('build').onclick=showShop;$('rotate').onclick=()=>{if(placing)placing.rot=(placing.rot+Math.PI/2)%(Math.PI*2);};$('cancel').onclick=endPlacement;$('sell').onclick=()=>{if(!placing?.id)return;const id=placing.id,price=catalog[placing.type].price;endPlacement();S.furniture=S.furniture.filter(f=>f.id!==id);S.money+=price;syncFurniture();save();toast('Meuble revendu · +'+price+' €');};$('confirm').onclick=commitPlacement;
$('pause').onclick=()=>{save();modal(`<div class="eyebrow">PRENEZ VOTRE TEMPS</div><h2>Pause café.</h2><p>${storageOK?'Votre progression est sauvegardée sur cet appareil.':'La sauvegarde est indisponible dans ce navigateur.'}</p><button class="primary" id="resume">Reprendre</button><button class="secondary" id="instructions">Guide & recette</button><button class="secondary" id="reset">Nouvelle partie</button>`);$('resume').onclick=resume;$('instructions').onclick=showHelp;$('reset').onclick=()=>{modal('<h2>Repartir de zéro ?</h2><p>Votre sauvegarde actuelle sera effacée sur cet appareil.</p><button class="primary" id="reallyReset">Effacer et recommencer</button><button class="secondary" id="keep">Garder ma partie</button>');$('keep').onclick=resume;$('reallyReset').onclick=()=>{resetting=true;paused=true;try{localStorage.removeItem(KEY);}catch{}const u=new URL(location.href);u.searchParams.set('v','1.3');u.searchParams.set('reset',Date.now().toString());location.replace(u.toString());};};};
const stick=$('joystick');let joyId=null;function stickMove(e){const r=stick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,limit=Math.max(18,r.width*.46),n=Math.max(1,Math.hypot(x,y)/limit),travel=Math.max(14,r.width*.32);joy.x=x/n/limit;joy.y=y/n/limit;stick.firstElementChild.style.transform=`translate(${joy.x*travel}px,${joy.y*travel}px)`;}
stick.onpointerdown=e=>{if(paused)return;joyId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===joyId)stickMove(e);};function clearStick(){joyId=null;joy.x=joy.y=0;stick.firstElementChild.style.transform='';}stick.onpointerup=clearStick;stick.onpointercancel=clearStick;
$('world').onpointerdown=e=>{if(paused)return;pointerDown={id:e.pointerId,x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(!pointerDown||pointerDown.id!==e.pointerId||paused)return;const dx=e.clientX-pointerDown.x,dy=e.clientY-pointerDown.y;yaw-=dx*.004;pitch=Math.max(-1.2,Math.min(1.15,pitch-dy*.004));pointerDown.x=e.clientX;pointerDown.y=e.clientY;};$('world').onpointerup=$('world').onpointercancel=()=>pointerDown=null;
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!e.repeat&&e.code==='KeyE')interact();if(!e.repeat&&e.code==='KeyR'&&placing)$('rotate').click();if(e.code==='Escape'){if(placing)endPlacement();else if(!paused)$('pause').click();}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{clearStick();Object.keys(keys).forEach(k=>keys[k]=false);});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(!paused)$('pause').click();}});window.addEventListener('pagehide',save);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
syncFurniture();ui();showWelcome();requestAnimationFrame(frame);
// Readable development hook for automated gameplay verification.
window.restaurant={get state(){return S;},camera,scene,catalog,route,ready,validPlacement,spawnClient,updateClients,save,interact,signAction,syncFurniture,beginPlacement,commitPlacement,endPlacement,resume,finishJob(){if(job){job.done();job=null;$('progress').style.display='none';}},aim(kind,id){target=kind==='sign'?sign:kind==='client'?clientMeshes.get(id):furnitureMeshes.get(id);},setPaused(v){paused=v;}};
