'use strict';
const $=s=>document.getElementById(s), KEY='atable-v1-save';
const catalog={table:{name:'Table bistro',price:65,w:1.3,d:1.1},chair:{name:'Chaise sauge',price:20,w:.52,d:.56},till:{name:'Caisse',price:70,w:1,d:.7},fridge:{name:'Réfrigérateur',price:100,w:.85,d:.8},prep:{name:'Plan de travail',price:65,w:1.4,d:.75},stove:{name:'Plaque de cuisson',price:90,w:1,d:.8}};
const customerNames=['Lina','Noah','Jade','Malo','Inès','Louis','Nina','Sacha','Maya','Tom','Zoé','Eliott','Léa','Adam','Lou','Nolan'];
const setupLabels={table:'table',chair:'chaise',till:'caisse',fridge:'réfrigérateur',prep:'plan de travail',stove:'plaque de cuisson'};
function clientName(c){return customerNames[(Math.max(1,c?.id||1)-1)%customerNames.length];}
function setupState(){const counts=Object.fromEntries(Object.keys(catalog).map(t=>[t,S.furniture.filter(f=>f.type===t).length]));return {counts,missing:[['table',1],['chair',2],['till',1],['fridge',1],['prep',1],['stove',1]].filter(([t,n])=>counts[t]<n)};}
const fresh=()=>({version:1,money:900,owned:false,day:1,open:false,closing:false,elapsed:0,spawn:2,stock:6,hand:'',furniture:[],clients:[],nextId:1,served:0,lost:0,revenue:0,expense:0,totalServed:0,rating:100,cook:0,cookReady:false,pos:{x:1.9,z:8,yaw:0,pitch:-.21}});
let S=fresh(),loaded=false,storageOK=true;try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===1&&Array.isArray(raw.furniture)&&Number.isFinite(raw.money)){S=raw;loaded=true;}}catch(e){storageOK=false;}
let paused=true,buildMode=false,placing=null,ghost=null,target=null,job=null,toastTime=0,autoSave=0,uiTime=0,yaw=S.pos.yaw,pitch=S.pos.pitch;const keys={},joy={x:0,y:0};
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7d5d1');scene.fog=new THREE.Fog('#b7d5d1',23,65);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.06,80);camera.rotation.order='YXZ';camera.position.set(S.pos.x,1.65,S.pos.z);camera.rotation.set(pitch,yaw,0);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('panel').innerHTML='<h2>La 3D est indisponible</h2><p>Ouvre ce jeu dans Safari ou Chrome avec WebGL activé.</p>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
scene.add(new THREE.HemisphereLight('#fff5d9','#769891',2.2));const sun=new THREE.DirectionalLight('#fff2d2',2.6);sun.position.set(-6,12,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12});sun.shadow.bias=-.002;scene.add(sun);
const mats={};function mat(c){return mats[c]||(mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.8}));}
function box(g,w,h,d,x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function cyl(g,r,h,x,y,z,c,r2=r){const m=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,12),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function label(g,text,x,y,z,w=2,h=.5,bg='#21483c',fg='#f7f0d5'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=fg;ctx.font='bold 48px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,66);const tx=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tx,side:THREE.DoubleSide}));m.position.set(x,y,z);g.add(m);return m;}
const world=new THREE.Group();scene.add(world);
box(world,80,.2,80,0,-.2,0,'#87a89b');box(world,24,.1,7,0,-.06,8,'#cecfc0');box(world,30,.04,4,0,-.08,13,'#7c8c87');for(let x=-12;x<13;x+=4)box(world,1.5,.02,.09,x,-.05,13,'#e9e2c7');
box(world,10,.16,10,0,-.09,-1,'#dbc5a0');box(world,10.3,.18,10.3,0,3.65,-1,'#eee4cd');for(let x=-5;x<5;x+=1)for(let z=-6;z<4;z+=1)box(world,.985,.02,.985,x+.5,.005,z+.5,(Math.round(x+z)%2)?'#e3d4ba':'#ecdfc8');
box(world,.22,3.6,10,-5,1.8,-1,'#ebdfc6');box(world,.22,3.6,10,5,1.8,-1,'#ebdfc6');box(world,10,3.6,.2,0,1.8,-6,'#bac8a6');
box(world,3.6,1.1,.2,-3.2,.55,4,'#385d4b');box(world,3.6,1.1,.2,3.2,.55,4,'#385d4b');box(world,10,.7,.28,0,3.3,4,'#365d4b');for(let x of [-5,-1.4,1.4,5])box(world,.15,3.3,.3,x,1.65,4,'#365d4b');
const glassmat=new THREE.MeshStandardMaterial({color:'#bde4d9',transparent:true,opacity:.16,roughness:.2});for(let x of [-3.2,3.2]){const m=box(world,3.4,1.8,.04,x,2,4,'#dcebe0');m.material=glassmat;box(world,3.6,.08,.4,x,1.13,4,'#eee7cf');}
box(world,10.5,.2,1.3,0,3.75,4.2,'#e5ba7c');for(let x=-5;x<5;x+=.6)box(world,.3,.03,1.3,x,3.87,4.2,'#f8eacc');label(world,'À  T A B L E',0,3.32,4.17,3,.45);
for(let z of [-5.85]){box(world,9.8,.12,.12,0,1.05,z,'#6c886d');box(world,9.8,.7,.08,0,.4,z,'#75906f');}for(let x of [-4.86,4.86])box(world,.1,.8,9.7,x,.4,-1,'#75906f');
for(let x of [-2.7,2.7]){cyl(world,.04,.5,x,3.1,-2,'#2f4941');cyl(world,.5,.2,x,2.8,-2,'#d6a25d',.18);const l=new THREE.PointLight('#ffe0a7',7,7,2);l.position.set(x,2.6,-2);scene.add(l);}
for(let x of [-5.8,5.8]){cyl(world,.38,.7,x,.35,4.5,'#b97955',.5);for(let i=0;i<4;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.5,0),mat(i%2?'#719369':'#547b59'));m.position.set(x+Math.sin(i)*.2,.95+i*.2,4.5+Math.cos(i)*.15);world.add(m);}}
for(let x of [-11,11]){box(world,6,7,8,x,3.5,-2,'#c8bdab');box(world,6,.2,8.5,x,7,-2,'#71837b');for(let y of [2,4.5])for(let a of [-1.5,1.5])box(world,1.1,1.6,.05,x+a,y,2.05,'#7d9e98');}
const sign=new THREE.Group();sign.position.set(1.9,0,5.15);box(sign,.08,1.35,.1,-.42,.68,0,'#936e49');box(sign,.08,1.35,.1,.42,.68,0,'#936e49');box(sign,1.05,.95,.15,0,1,0,'#c89b67');let signText=label(sign,'À VENDRE',0,1.05,.09,.95,.32);scene.add(sign);sign.userData.kind='sign';const backSign=label(sign,'À VENDRE',0,1.05,-.09,.95,.32);backSign.rotation.y=Math.PI;
const furnitureMeshes=new Map(),clientMeshes=new Map();
function dispose(g){g.traverse(m=>{if(m.geometry)m.geometry.dispose();if(m.material?.map){m.material.map.dispose();m.material.dispose();}});g.removeFromParent();}
function furnitureMesh(f){const g=new THREE.Group();const wood='#bd8e59',metal='#536b62',green='#719478';switch(f.type){case'table':box(g,1.3,.1,1.1,0,.83,0,wood);for(let x of [-.5,.5])for(let z of [-.4,.4])box(g,.08,.78,.08,x,.39,z,metal);cyl(g,.08,.14,0,.95,0,'#f0e1bf');break;case'chair':box(g,.52,.09,.52,0,.47,0,green);box(g,.52,.54,.08,0,.79,.24,green);for(let x of [-.2,.2])for(let z of [-.2,.2])box(g,.045,.45,.045,x,.23,z,metal);break;case'fridge':box(g,.85,1.9,.8,0,.95,0,'#d8e3d5');box(g,.78,1.12,.06,0,.7,.43,'#eef1df');box(g,.78,.57,.06,0,1.57,.43,'#eef1df');box(g,.04,.4,.06,.28,.95,.49,metal);label(g,'FRAIS',0,1.6,.47,.55,.13);break;case'prep':box(g,1.4,.82,.75,0,.41,0,'#789581');box(g,1.48,.09,.83,0,.88,0,'#efe7d3');box(g,.6,.025,.4,-.15,.945,0,wood);box(g,.25,.025,.1,.35,.945,.13,metal);break;case'stove':box(g,1,.85,.8,0,.425,0,'#d1d9cf');box(g,1.05,.06,.84,0,.88,0,'#384d46');for(let x of [-.25,.25])for(let z of [-.2,.2])cyl(g,.15,.018,x,.922,z,'#182f2a');box(g,.76,.4,.03,0,.43,.415,'#344d45');for(let x of [-.3,0,.3])cyl(g,.04,.045,x,.75,.43,'#c49658');break;case'till':box(g,1,.9,.7,0,.45,0,wood);box(g,1.06,.07,.76,0,.94,0,'#ede6d0');box(g,.4,.08,.32,0,1.02,0,metal);const screen=box(g,.4,.28,.06,0,1.19,-.06,'#263f35');screen.rotation.x=-.25;label(g,'€',0,1.2,-.015,.16,.16,'#27493f','#ddecaa');break;}
g.position.set(f.x,0,f.z);g.rotation.y=f.rot||0;g.userData.kind='furniture';g.userData.id=f.id;return g;}
function syncFurniture(){for(const g of furnitureMeshes.values())dispose(g);furnitureMeshes.clear();for(const f of S.furniture){const g=furnitureMesh(f);scene.add(g);furnitureMeshes.set(f.id,g);}}
function person(c){
const g=new THREE.Group(),body=new THREE.Group(),walk=new THREE.Group(),sit=new THREE.Group();g.add(body,walk,sit);
const shirts=['#b37556','#5b8588','#a8945d','#977a99','#587861','#c17e5f','#6b728f','#8a725d'],pants=['#354d50','#32423c','#4f4640','#3f4654'],skins=['#e0b18c','#c98f68','#f0c6a0','#9f694b'],hairs=['#524638','#342d28','#806044','#272a28'];
const idx=(c.id||1)-1,shirt=shirts[idx%shirts.length],skin=skins[(idx*3)%skins.length],hair=hairs[(idx*5)%hairs.length],pant=pants[(idx*7)%pants.length];
cyl(body,.19,.55,0,.94,0,shirt,.25);cyl(body,.15,.2,0,1.35,0,skin);const head=new THREE.Mesh(new THREE.SphereGeometry(.19,10,8),mat(skin));head.position.y=1.48;body.add(head);
if(idx%3===0){box(body,.34,.12,.3,0,1.64,0,hair);}else if(idx%3===1){const h=cyl(body,.2,.12,0,1.64,0,hair);h.scale.z=.9;}else{box(body,.28,.09,.32,0,1.66,-.03,hair);box(body,.08,.18,.08,-.16,1.55,.03,hair);}
for(let x of [-.12,.12]){box(walk,.13,.6,.15,x,.38,0,pant);box(walk,.17,.12,.27,x,.08,-.05,'#2b413b');box(sit,.15,.14,.4,x,.48,-.13,pant);box(sit,.13,.36,.14,x,.25,-.3,pant);box(sit,.17,.1,.26,x,.06,-.35,'#2b413b');}
for(let x of [-.29,.29])box(body,.1,.48,.13,x,.91,0,skin);g.userData={kind:'client',id:c.id,body,walk,sit};scene.add(g);return g;}
function dims(f,pad=0){let d=catalog[f.type],swap=Math.abs(Math.sin(f.rot||0))>.5;return {w:(swap?d.d:d.w)/2+pad,d:(swap?d.w:d.d)/2+pad};}
function insideFurniture(x,z,f,pad=.22){const d=dims(f,pad);return Math.abs(x-f.x)<d.w&&Math.abs(z-f.z)<d.d;}
function blocked(x,z,ignore=null,list=S.furniture,pad=.23){if(x< -4.65||x>4.65||z< -5.65||z>9.5)return true;if(Math.abs(z-4)<.35&&Math.abs(x)>1.1)return true;if(!S.owned&&z<4.4)return true;return list.some(f=>f.id!==ignore&&insideFurniture(x,z,f,pad));}
// Navigation grid includes the entrance and street. Furniture remains an obstacle.
function route(start,end,ignore=null,list=S.furniture){const step=.4;const gx=x=>Math.round((x+4.4)/step),gz=z=>Math.round((z+5.4)/step),point=(x,z)=>({x:x*step-4.4,z:z*step-5.4});const sx=gx(start.x),sz=gz(start.z),tx=gx(end.x),tz=gz(end.z);const id=(x,z)=>x+','+z,queue=[[sx,sz]],parents=new Map([[id(sx,sz),null]]);let found=null;for(let i=0;i<queue.length&&i<2500;i++){const [x,z]=queue[i];if(Math.hypot(x-tx,z-tz)<=1){found=[x,z];break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,nz=z+dz,k=id(nx,nz),p=point(nx,nz);if(parents.has(k)||blocked(p.x,p.z,ignore,list,.17))continue;parents.set(k,[x,z]);queue.push([nx,nz]);}}if(!found)return null;const out=[];let cur=found;while(cur){out.push(point(...cur));cur=parents.get(id(...cur));}return out.reverse();}
function chairs(){return S.furniture.filter(f=>f.type==='chair'&&S.furniture.some(t=>t.type==='table'&&Math.hypot(t.x-f.x,t.z-f.z)<1.7));}
function seatSpot(f){return{x:f.x,z:f.z};}
function ready(){const need=['table','chair','till','fridge','prep','stove'];return need.every(t=>S.furniture.some(f=>f.type===t))&&S.furniture.filter(f=>f.type==='chair').length>=2&&chairs().filter(c=>route({x:0,z:5},seatSpot(c),c.id)).length>=2;}
function save(){S.pos={x:camera.position.x,z:camera.position.z,yaw,pitch};try{localStorage.setItem(KEY,JSON.stringify(S));storageOK=true;}catch{storageOK=false;} }
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;toastTime=3.5;}
function modal(html){paused=true;joy.x=joy.y=0;Object.keys(keys).forEach(k=>keys[k]=false);$('modal').hidden=false;$('panel').innerHTML=html;document.exitPointerLock?.();}
function resume(){paused=false;$('modal').hidden=true;}
function showWelcome(){modal(`<div class="eyebrow">SIMULATEUR DE RESTAURANT · V1</div><h1>Une adresse.<br>Votre histoire.</h1><p>Un local vide, quelques économies et votre premier service à inventer.</p><div class="tags"><span>3D · Première personne</span><span>Sauvegarde locale</span></div><p><b>Déplacez-vous à gauche.</b> Glissez à droite pour regarder. Visez un objet, puis touchez le bouton d’action.</p><button class="primary" id="start">${loaded?'Reprendre mon restaurant':'Commencer l’aventure'}</button><button class="secondary" id="welcomeHelp">Voir les commandes</button>`);$('start').onclick=()=>{resume();if(!storageOK)toast('Sauvegarde indisponible dans ce navigateur.');};$('welcomeHelp').onclick=showHelp;}
function showHelp(){modal(`<div class="eyebrow">LE CARNET DU CHEF</div><h2>Votre premier service</h2><ol class="steps"><li>Achetez le local : <b>250 €</b>, sur la pancarte devant.</li><li>Entrez, puis ouvrez <b>Aménager</b>. Achetez chaque équipement et deux chaises.</li><li>Placez les chaises près de la table. Laissez des passages et la porte libres.</li><li>Ouvrez avec la pancarte. Prenez la commande du client.</li><li>Réfrigérateur → ingrédients. Plan de travail → préparer. Plaque → cuire. Plan de travail → dresser.</li><li>Servez le client, puis encaissez à la caisse après son repas.</li></ol><p>Un burger : <b>18 € + pourboire</b>. 6 portions offertes ; réassort de 6 portions à 18 €. Un service dure 4 minutes, puis finit après le départ des clients.</p><p>Mobile : joystick à gauche, vue à droite. Ordinateur : ZQSD / WASD / flèches, glisser la souris pour regarder, E pour agir, R pour pivoter. La pause arrête les clients et la cuisson.</p><button class="primary" id="back">C’est parti</button>`);$('back').onclick=resume;}
function showShop(){if(!S.owned)return toast('Achetez d’abord le local sur la pancarte.');if(S.open||S.clients.length||S.closing)return toast('Aménagez entre deux journées, sans client.');if(job)return;buildMode=true;const st=setupState();const req=[['table',1],['chair',2],['till',1],['fridge',1],['prep',1],['stove',1]];modal(`<div class="eyebrow">ATELIER · ${S.money} € DISPONIBLES</div><h2>Faites-en votre lieu.</h2><p>Choisissez un meuble, visez le sol, pivotez et validez. Aucun débit avant validation.</p><div class="setupCheck"><div class="setupTitle"><b>Ouverture du restaurant</b><span>${st.missing.length?'Équipement à terminer':'Prêt à ouvrir ✓'}</span></div><div class="setupGrid">${req.map(([t,n])=>`<span class="${st.counts[t]>=n?'done':''}">${st.counts[t]>=n?'✓':'○'} ${catalog[t].name}${n>1?' · '+Math.min(st.counts[t],n)+'/'+n:''}</span>`).join('')}</div></div><div class="shop">${Object.entries(catalog).map(([type,d])=>`<button class="item" data-buy="${type}" ${S.money<d.price?'disabled':''}><b>${d.name}</b><small>${S.furniture.filter(f=>f.type===type).length} installé(s)</small><em>${d.price} €</em></button>`).join('')}</div><p>Pour déplacer un meuble existant, fermez ce panneau et visez-le en mode aménagement.</p><button class="primary" id="arrange">Déplacer des meubles</button><button class="secondary" id="shopClose">Terminer l’aménagement</button>`);document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>beginPlacement(b.dataset.buy));$('arrange').onclick=resume;$('shopClose').onclick=()=>{buildMode=false;resume();};}
function beginPlacement(type,id=null){const f=S.furniture.find(f=>f.id===id);placing={type,id,rot:f?.rot||0,x:f?.x||0,z:f?.z||0,valid:false};if(id)furnitureMeshes.get(id).visible=false;ghost=furnitureMesh({...placing,id:-1});ghost.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.transparent=true;m.material.opacity=.5;}});scene.add(ghost);$('placement').hidden=false;$('sell').hidden=!id;resume();}
function endPlacement(){if(placing?.id)furnitureMeshes.get(placing.id).visible=true;if(ghost){ghost.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose();}});scene.remove(ghost);}placing=null;ghost=null;$('placement').hidden=true;}
function validPlacement(f){const d=dims(f,.1);if(Math.abs(f.x)+d.w>4.8||f.z-d.d< -5.8||f.z+d.d>3.75)return false;if(Math.abs(f.x)<1.35+d.w&&f.z+d.d>2.9)return false;if(S.furniture.some(o=>{if(o.id===f.id)return false;let a=dims(f,.07),b=dims(o);return Math.abs(f.x-o.x)<a.w+b.w&&Math.abs(f.z-o.z)<a.d+b.d;}))return false;if(insideFurniture(camera.position.x,camera.position.z,f,.25))return false;const list=S.furniture.filter(o=>o.id!==f.id).concat(f);if(!route(camera.position,{x:0,z:5},null,list))return false;return true;}
function commitPlacement(){if(!placing?.valid)return toast('Position bloquée : libérez le passage ou reculez.');if(!placing.id&&S.money<catalog[placing.type].price)return toast('Budget insuffisant.');const f={id:placing.id||S.nextId++,type:placing.type,x:placing.x,z:placing.z,rot:placing.rot};if(placing.id)S.furniture=S.furniture.map(o=>o.id===f.id?f:o);else{S.money-=catalog[f.type].price;S.furniture.push(f);}endPlacement();syncFurniture();save();toast('Meuble installé. Visez-le pour le déplacer.');}
function timed(label,duration,done){if(job)return;job={label,total:duration,left:duration,done};$('progress').style.display='block';}
function signAction(){if(!S.owned){modal('<div class="eyebrow">VOTRE FUTURE ADRESSE</div><h2>Les clés sont à vous.</h2><p>Un local de 100 m² pour <b>250 €</b>. Il vous restera <b>650 €</b> pour l’équiper. Six portions sont offertes à l’ouverture.</p><button class="primary" id="buyLocal">Acheter · 250 €</button><button class="secondary" id="noBuy">Plus tard</button>');$('buyLocal').onclick=()=>{if(S.money<250)return;S.money-=250;S.owned=true;resume();save();toast('Bienvenue chez vous ! Entrez par la porte centrale.');};$('noBuy').onclick=resume;return;}if(S.open){S.open=false;S.closing=true;toast('Dernières commandes : terminez le service en cours.');save();return;}if(S.closing)return toast('Servez et encaissez les derniers clients.');if(!ready())return toast('Il faut tous les équipements, deux chaises près d’une table et des passages accessibles.');buildMode=false;S.open=true;S.elapsed=0;S.spawn=1;S.revenue=0;S.expense=0;S.served=0;S.lost=0;save();toast('Jour '+S.day+' · Votre restaurant est ouvert !');}
function interact(){if(paused||placing||job)return;if(!target)return;const kind=target.userData.kind;if(kind==='sign'){signAction();return;}if(kind==='client'){const c=S.clients.find(c=>c.id===target.userData.id);if(!c)return;if(c.state==='order'){c.state='wait';toast('Commande : un burger maison.');save();}else if(c.state==='wait'&&S.hand==='meal'){S.hand='';c.state='eat';c.timer=0;c.satisfaction=Math.max(20,Math.round(c.patience/100*100));toast('Bon appétit !');save();}else toast(c.state==='pay'?'Encaissez à la caisse.':'Ce client attend '+(c.state==='wait'?'son burger.':'un instant.'));return;}
const f=S.furniture.find(f=>f.id===target.userData.id);if(!f)return;if(buildMode){beginPlacement(f.type,f.id);return;}switch(f.type){case'fridge':if(S.hand)return toast('Terminez d’abord ce que vous avez en main.');if(!S.stock){if(S.money<18)return toast('Réassort : 18 € nécessaires.');modal('<h2>Remplir le réfrigérateur</h2><p>6 portions de pain, légumes et steak pour 18 €.</p><button class="primary" id="restock">Acheter · 18 €</button><button class="secondary" id="restockCancel">Retour</button>');$('restock').onclick=()=>{if(S.money>=18){S.money-=18;S.stock+=6;S.expense+=18;}resume();save();};$('restockCancel').onclick=resume;}else{S.stock--;S.hand='ingredients';save();toast('Pain, légumes et steak récupérés.');}break;case'prep':if(S.hand==='ingredients')timed('Préparation des ingrédients',2,()=>{S.hand='prepared';toast('Prêt pour la cuisson.');});else if(S.hand==='cooked')timed('Dressage du burger',1.5,()=>{S.hand='meal';toast('Burger prêt à servir !');});else toast('Apportez les ingrédients, ou le burger cuit à dresser.');break;case'stove':if(S.cookReady){if(S.hand)return toast('Il faut les mains libres.');S.cookReady=false;S.hand='cooked';save();toast('Cuisson terminée. Dressez sur le plan de travail.');}else if(S.cook>0)toast('Cuisson : encore '+Math.ceil(S.cook)+' s.');else if(S.hand==='prepared'){S.hand='';S.cook=5;save();toast('Cuisson lancée · 5 secondes.');}else toast('Préparez les ingrédients sur le plan de travail.');break;case'till':{const c=S.clients.find(c=>c.state==='pay');if(!c)return toast('Aucun paiement en attente.');const tip=Math.round(c.satisfaction/100*6),cash=18+tip;S.money+=cash;S.revenue+=cash;S.served++;S.totalServed++;S.rating=Math.round((S.rating*4+c.satisfaction)/5);leave(c);save();toast('+'+cash+' € · dont '+tip+' € de pourboire !');break;}default:toast('Installez les chaises près des tables.');}}
function leave(c){c.state='leave';c.path=route(c,{x:0,z:8.5},c.chair)||[{x:0,z:4.5},{x:0,z:8.5}];c.pathIndex=0;c.timer=0;}
function spawnClient(){const available=chairs().filter(f=>!S.clients.some(c=>c.chair===f.id&&c.state!=='leave'));for(const chair of available){const path=route({x:0,z:8.5},seatSpot(chair),chair.id);if(!path)continue;const c={id:S.nextId++,chair:chair.id,x:0,z:8.5,state:'walk',path:path.concat([seatSpot(chair)]),pathIndex:0,patience:100,timer:0,satisfaction:100};S.clients.push(c);return true;}return false;}
function finishDay(){S.closing=false;const day=S.day;S.day++;save();modal(`<div class="eyebrow">SERVICE TERMINÉ · JOUR ${day}</div><h2>Une journée bien remplie.</h2><div class="stats"><div><b>${S.served}</b><small>CLIENTS SERVIS</small></div><div><b>${S.revenue-S.expense} €</b><small>SOLDE DU SERVICE*</small></div></div><p>${S.lost?S.lost+' client(s) sont partis avant le repas.':'Vous avez pris soin de chaque client.'}<br>Satisfaction moyenne : ${S.rating} %.</p><p>*Encaissements moins réassorts achetés pendant ce service. Les portions offertes ne sont pas facturées.</p><button class="primary" id="nextDay">Préparer le jour ${S.day}</button>`);$('nextDay').onclick=resume;}
function updateClients(dt){if(S.open){S.elapsed+=dt;S.spawn-=dt;if(S.spawn<=0){spawnClient();S.spawn=S.totalServed<2?20:13;}if(S.elapsed>=240){S.open=false;S.closing=true;toast('Le service se termine. Occupez-vous des derniers clients.');}}
for(const c of [...S.clients]){c.timer+=dt;if(c.state==='walk'||c.state==='leave'){const p=c.path[c.pathIndex];if(p){const dx=p.x-c.x,dz=p.z-c.z,dist=Math.hypot(dx,dz),speed=dt*1.1;if(dist<speed){c.x=p.x;c.z=p.z;c.pathIndex++;}else{c.x+=dx/dist*speed;c.z+=dz/dist*speed;c.angle=Math.atan2(-dx,-dz);}}else if(c.state==='leave'){S.clients=S.clients.filter(a=>a!==c);const g=clientMeshes.get(c.id);if(g)dispose(g);clientMeshes.delete(c.id);}else{c.state='order';c.timer=0;toast('Un client est prêt à commander.');}}
else if(c.state==='order'||c.state==='wait'){c.patience-=dt*(c.state==='order'?.32:.65);if(c.patience<=0){S.lost++;S.rating=Math.max(0,S.rating-8);leave(c);toast('Un client a perdu patience.');}}
else if(c.state==='eat'&&c.timer>=9){c.state='pay';c.timer=0;toast('Un client souhaite payer. Rendez-vous à la caisse.');}
}
if(S.closing&&!S.clients.length)finishDay();}
const ray=new THREE.Raycaster(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let pointerDown=null;
function pick(){target=null;ray.setFromCamera({x:0,y:0},camera);const objects=[sign,...furnitureMeshes.values(),...clientMeshes.values()];const hits=ray.intersectObjects([...objects,world],true);for(const h of hits){if(h.distance>3.2)break;let o=h.object;while(o.parent&&!o.userData.kind)o=o.parent;if(o.visible&&o.userData.kind){target=o;break;}else break;}}
function actionText(){if(!target)return['Approchez-vous et visez un objet',''];const d=target.userData;if(d.kind==='sign')return[S.owned?'Pancarte du restaurant':'Local commercial',!S.owned?'Acheter · 250 €':S.open?'Fermer le service':S.closing?'Service en cours':'Ouvrir · Jour '+S.day];if(d.kind==='client'){const c=S.clients.find(c=>c.id===d.id);return[clientName(c)+' · '+Math.ceil(c?.patience||0)+' % de patience',c?.state==='order'?'Prendre la commande':c?.state==='wait'?(S.hand==='meal'?'Servir le burger':'Burger en attente'):c?.state==='pay'?'Paiement à la caisse':c?.state==='eat'?'Bon appétit':'Client en déplacement'];}const f=S.furniture.find(f=>f.id===d.id);if(!f)return['',''];if(buildMode)return[catalog[f.type].name,'Déplacer'];const names={fridge:S.stock?'Prendre les ingrédients':'Réassort · 18 €',prep:S.hand==='cooked'?'Dresser le burger':'Préparer les ingrédients',stove:S.cookReady?'Récupérer le burger':S.cook>0?'Cuisson · '+Math.ceil(S.cook)+' s':'Lancer la cuisson',till:'Encaisser',table:'Table bistro',chair:'Chaise'};return[catalog[f.type].name,names[f.type]];}
const handNames={'':'MAINS LIBRES',ingredients:'INGRÉDIENTS FRAIS',prepared:'BURGER À CUIRE',cooked:'BURGER À DRESSER',meal:'BURGER PRÊT À SERVIR'};
function goal(){if(!S.owned)return'Achetez le local sur la pancarte devant vous.';if(placing)return'Déplacez le viseur sur le sol, puis validez.';if(!ready()){const st=setupState();if(st.missing.length){const labels=st.missing.slice(0,2).map(([t,n])=>{const left=n-st.counts[t];return left+' '+setupLabels[t]+(left>1?'s':'');});return'Encore '+labels.join(' et ')+(st.missing.length>2?'…':'')+' à installer.';}return'Libérez un passage entre l’entrée, les chaises et les équipements.';}if(!S.open&&!S.closing)return'Votre restaurant est prêt. Ouvrez avec la pancarte.';if(S.clients.some(c=>c.state==='pay'))return'Un client veut payer. Encaissez à la caisse.';if(S.hand==='meal')return'Servez le burger au client qui attend.';if(S.hand==='cooked')return'Dressez le repas sur le plan de travail.';if(S.cookReady)return'La cuisson est terminée ! Récupérez le burger.';if(S.cook>0)return'La cuisson est en cours. Préparez le prochain service.';if(S.hand==='prepared')return'Apportez les ingrédients préparés à la plaque.';if(S.hand==='ingredients')return'Préparez les ingrédients sur le plan de travail.';if(S.clients.some(c=>c.state==='wait'))return'Récupérez une portion dans le réfrigérateur.';if(S.clients.some(c=>c.state==='order'))return'Approchez-vous du client pour prendre sa commande.';return'Accueillez vos clients. Votre bistrot prend vie.';}
let lastSign='';function ui(){ $('money').textContent=S.money+' €';$('day').textContent='JOUR '+S.day;$('goal').textContent=goal();$('hand').textContent=handNames[S.hand]||'MAINS LIBRES';let status=S.open?'Ouvert · '+Math.max(0,Math.ceil((240-S.elapsed)/60))+' min':S.closing?'Dernier service':S.owned?'Fermé · '+S.stock+' portions':'À vendre';if(S.cook>0)status+=' · Cuisson '+Math.ceil(S.cook)+' s';else if(S.cookReady)status+=' · Cuisson prête';$('statusText').textContent=status+(buildMode?' · Aménagement':'');$('status').querySelector('i').style.background=S.open?'#bde79b':'#f7c97d';const [title,act]=actionText();$('target').textContent=job?job.label:title;$('act').textContent=job?'En cours…':act||'';$('act').hidden=!job&&!act;$('act').disabled=!target||!!job;$('context').classList.toggle('idle',!target&&!job);$('context').hidden=!!placing;$('crosshair').classList.toggle('active',!!target&&!placing);const dp=$('dayProgress');dp.classList.toggle('show',S.open||S.closing);dp.firstElementChild.style.width=Math.min(100,(S.elapsed/240)*100)+'%';$('orders').innerHTML=S.clients.filter(c=>!['walk','leave'].includes(c.state)).slice(0,4).map(c=>`<div class="order"><strong>${c.state==='order'?'Une commande ?':c.state==='eat'?'Bon appétit !':c.state==='pay'?'Paiement en attente':'1 × Burger maison'}</strong><small>${clientName(c)} · ${c.state==='pay'?'Caisse':Math.ceil(c.patience)+' % de patience'}</small><div class="bar"><span style="width:${Math.max(0,c.patience)}%;background:${c.patience<30?'#c97452':'#488e65'}"></span></div></div>`).join('');const st=!S.owned?'À VENDRE':S.open?'OUVERT':'FERMÉ';if(lastSign!==st){for(const m of [signText,backSign]){const ctx=m.material.map.image.getContext('2d');ctx.fillStyle='#21483c';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f7f0d5';ctx.font='bold 48px sans-serif';ctx.textAlign='center';ctx.fillText(st,256,66);m.material.map.needsUpdate=true;}lastSign=st;}}
function updatePlacement(){ray.setFromCamera({x:0,y:-.18},camera);const p=new THREE.Vector3();if(!ray.ray.intersectPlane(floorPlane,p)||p.distanceTo(camera.position)>6){p.copy(camera.position);p.x-=Math.sin(yaw)*2.5;p.z-=Math.cos(yaw)*2.5;}placing.x=Math.round(p.x*10)/10;placing.z=Math.round(p.z*10)/10;placing.valid=validPlacement(placing);ghost.position.set(placing.x,.015,placing.z);ghost.rotation.y=placing.rot;ghost.traverse(m=>{if(m.isMesh)m.material.color.set(placing.valid?'#96daa2':'#e78065');});$('confirm').disabled=!placing.valid;$('placeHint').textContent=placing.valid?'Position libre · '+(placing.id?'Déplacement':catalog[placing.type].price+' €'):'Position bloquée · Visez un sol libre';}
const held=new THREE.Group();camera.add(held);scene.add(camera);held.position.set(.36,-.38,-.65);cyl(held,.19,.02,0,0,0,'#faf2d9');cyl(held,.13,.065,0,.035,0,'#b97338');cyl(held,.145,.024,0,.077,0,'#598b46');cyl(held,.12,.035,0,.105,0,'#694835');cyl(held,.135,.06,0,.15,0,'#dba657',.1);held.visible=false;
let previous=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-previous)/1000,.05);previous=now;if(!paused&&!document.hidden){let forward=(keys.KeyW||keys.KeyZ||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-joy.y,side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.KeyQ||keys.ArrowLeft?1:0)+joy.x;let n=Math.max(1,Math.hypot(forward,side));forward/=n;side/=n;let dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*dt*2.6,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*dt*2.6;if(!blocked(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!blocked(camera.position.x,camera.position.z+dz))camera.position.z+=dz;camera.rotation.set(pitch,yaw,0);if(placing)updatePlacement();else pick();if(job){job.left-=dt;$('progress').firstElementChild.style.width=(1-job.left/job.total)*100+'%';if(job.left<=0){job.done();job=null;$('progress').style.display='none';save();}}if(S.cook>0){S.cook=Math.max(0,S.cook-dt);if(!S.cook){S.cookReady=true;toast('Le burger est cuit !');save();}}updateClients(dt);autoSave+=dt;if(autoSave>4){save();autoSave=0;}toastTime-=dt;if(toastTime<0)$('toast').style.opacity=0;}
for(const c of S.clients){let g=clientMeshes.get(c.id);if(!g){g=person(c);clientMeshes.set(c.id,g);}const seated=['order','wait','eat','pay'].includes(c.state);const moving=['walk','leave'].includes(c.state);g.position.set(c.x,moving?Math.abs(Math.sin(now*.008+c.id))*0.025:0,c.z);g.userData.body.position.y=seated?-.15:0;g.userData.body.rotation.z=moving?Math.sin(now*.01+c.id)*.018:0;g.userData.sit.visible=seated;g.userData.walk.visible=!seated;const chair=S.furniture.find(f=>f.id===c.chair);g.rotation.y=['walk','leave'].includes(c.state)?c.angle||0:chair?.rot||0;}
held.visible=!!S.hand;held.rotation.z=Math.sin(now*.003)*.025;uiTime+=dt;if(uiTime>.15){ui();uiTime=0;}renderer.render(scene,camera);}
$('act').onclick=interact;$('help').onclick=showHelp;$('build').onclick=showShop;$('rotate').onclick=()=>{if(placing)placing.rot=(placing.rot+Math.PI/2)%(Math.PI*2);};$('cancel').onclick=endPlacement;$('sell').onclick=()=>{if(!placing?.id)return;const id=placing.id,price=catalog[placing.type].price;endPlacement();S.furniture=S.furniture.filter(f=>f.id!==id);S.money+=price;syncFurniture();save();toast('Meuble revendu · +'+price+' €');};$('confirm').onclick=commitPlacement;
$('pause').onclick=()=>{save();modal(`<div class="eyebrow">PRENEZ VOTRE TEMPS</div><h2>Pause café.</h2><p>${storageOK?'Votre progression est sauvegardée sur cet appareil.':'La sauvegarde est indisponible dans ce navigateur.'}</p><button class="primary" id="resume">Reprendre</button><button class="secondary" id="instructions">Commandes et recette</button><button class="secondary" id="reset">Nouvelle partie</button>`);$('resume').onclick=resume;$('instructions').onclick=showHelp;$('reset').onclick=()=>{modal('<h2>Repartir de zéro ?</h2><p>Votre sauvegarde actuelle sera effacée sur cet appareil.</p><button class="primary" id="reallyReset">Effacer et recommencer</button><button class="secondary" id="keep">Garder ma partie</button>');$('keep').onclick=resume;$('reallyReset').onclick=()=>{try{localStorage.removeItem(KEY);}catch{}location.reload();};};};
const stick=$('joystick');let joyId=null;function stickMove(e){const r=stick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,n=Math.max(1,Math.hypot(x,y)/34);joy.x=x/n/34;joy.y=y/n/34;stick.firstElementChild.style.transform=`translate(${joy.x*27}px,${joy.y*27}px)`;}
stick.onpointerdown=e=>{if(paused)return;joyId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===joyId)stickMove(e);};function clearStick(){joyId=null;joy.x=joy.y=0;stick.firstElementChild.style.transform='';}stick.onpointerup=clearStick;stick.onpointercancel=clearStick;
$('world').onpointerdown=e=>{if(paused)return;pointerDown={id:e.pointerId,x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(!pointerDown||pointerDown.id!==e.pointerId||paused)return;const dx=e.clientX-pointerDown.x,dy=e.clientY-pointerDown.y;yaw-=dx*.004;pitch=Math.max(-1.2,Math.min(1.15,pitch-dy*.004));pointerDown.x=e.clientX;pointerDown.y=e.clientY;};$('world').onpointerup=$('world').onpointercancel=()=>pointerDown=null;
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!e.repeat&&e.code==='KeyE')interact();if(!e.repeat&&e.code==='KeyR'&&placing)$('rotate').click();if(e.code==='Escape'){if(placing)endPlacement();else if(!paused)$('pause').click();}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{clearStick();Object.keys(keys).forEach(k=>keys[k]=false);});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(!paused)$('pause').click();}});window.addEventListener('pagehide',save);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
syncFurniture();ui();showWelcome();requestAnimationFrame(frame);
// Readable development hook for automated gameplay verification.
window.restaurant={get state(){return S;},camera,scene,catalog,route,ready,validPlacement,spawnClient,updateClients,save,interact,signAction,syncFurniture,beginPlacement,commitPlacement,endPlacement,resume,finishJob(){if(job){job.done();job=null;$('progress').style.display='none';}},aim(kind,id){target=kind==='sign'?sign:kind==='client'?clientMeshes.get(id):furnitureMeshes.get(id);},setPaused(v){paused=v;}};
